### PR TITLE
Better handling of array query parameters

### LINKED ISSUE #316: collectionFormat is not specified for array query parameters in the generated swagger
This is because the check on parameter type in `specGenerator`.`buildParameter` for arrays is wrong (`parameter.type === 'array'` instead of `parameterType.type === 'array'`)

### PR DESCRIPTION
**Pull request by slapersonne**
This aims to better handle the array query parameters, with a fix for `collectionFormat` property generation in swagger.
CollectionFormat could then later be specified with a tag, but I kept the default value for this fix.

Close #316

### CODE REVIEW

File: src/metadataGeneration/tsoa.ts [hunk 1]
```diff
@@ -39,6 +39,11 @@ export namespace Tsoa {
     validators: Validators;
   }
 
+  export interface ArrayParameter extends Parameter {
```
Comment (endor) [inline src/metadataGeneration/tsoa.ts]: Why introduce this?

File: src/metadataGeneration/parameterGenerator.ts [hunk 2]
```diff
@@ -110,27 +110,35 @@ export class ParameterGenerator {
     const parameterName = (parameter.name as ts.Identifier).text;
     const type = this.getValidatedType(parameter, false);
 
+    const commonProperties = {
+      default: getInitializerValue(parameter.initializer, type),
+      description: this.getParameterDescription(parameter),
+      in: 'query' as 'query',
```
Comment (endor) [inline src/metadataGeneration/parameterGenerator.ts]: What does this do?

Comment (slapersonne) [reply src/metadataGeneration/parameterGenerator.ts]: This because `in` property is typed as `'query' | 'header' | 'path' | 'formData' | 'body' | 'body-prop' | 'request'`. With just `in: 'query'` for the definition, it is typed as `string` by default, so there is an incompatible type error when returning the parameter.
An alternative would be to use `as Tsoa.Parameter` for the return.

File: src/metadataGeneration/tsoa.ts (hunk 1 above)
Comment (slapersonne) [reply src/metadataGeneration/tsoa.ts]: To avoid defining the `collectionFormat` in `Parameter`, because it is specific to array parameters. There was already an `ArrayType` for array-specific types so I thought it would be fair to also have an `ArrayParameter`.

**Comment by endor** [comment]
Thanks. This looks good.
